"""Structured logs, one JSON object per line, always carrying `trace_id` · `request_id` ·
`job_id`.

Three ids, three different origins — this is where people get confused:

    trace_id    generated by OTel after instrumentation. Read from the current span, not
                passed by hand
    request_id  generated by us in `api/middleware.py` and put into contextvars. Returned
                to the client — this is the id someone quotes when reporting a problem
    job_id      generated when enqueueing into `queue/`. Links a request to the background
                work that follows

The logger does not know `trace_id` on its own: every log call must read the current span
and attach it. That is the only piece of wiring we write by hand, and it is what lets you
jump from one log line straight to the matching trace instead of hunting by timestamp.

If an id is missing it still logs and does not raise — logging that kills a request turns a
small problem into a large one.

**Printed to stdout, shipped nowhere.** Promtail collects container stdout and pushes it to
Loki; the same mechanism applies under K8s. That way this module does not know Loki exists,
and changing log backend later is an edit to `deploy/otel/promtail.yaml`.

`trace_id` goes in the **body** of the JSON line, not a Loki label: Loki creates one stream
per distinct label value, and trace_id is almost never repeated. Grafana still picks it up
via a derived field — see `deploy/grafana/datasources/`.
"""
